CREATE SCHEMA BULK_DML_SCHEMA;

SET search_path TO BULK_DML_SCHEMA;

-- Table to help demonstrate bulk DML.
CREATE TABLE ACCOUNTS (
    ACCOUNT_ID VARCHAR(36) NOT NULL PRIMARY KEY,
    ACCOUNT_NAME VARCHAR(50) NOT NULL
);

